import { ReactNode } from 'react'
import '../styles/global.scss'
import { font } from './fonts'
import { WordleProvider } from '@/context/wordleContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }: {children: ReactNode}) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <WordleProvider>
          {children}
        </WordleProvider>
      </body>
    </html>
  )
}
